apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab1
  name: dep-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-nginx
  template:
    metadata:
      labels:
        app: pod-nginx
    spec:
      containers:
      - name: ctn-nginx
        image: nginx
        ports:
        - containerPort: 80