apiVersion: v1
kind: Service
metadata:
  namespace: lab1
  name: node-port-nginx
spec:
  type: NodePort
  selector:
    app: pod-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081