apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab3
  name: dep-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-nginx-proxy
  template:
    metadata:
      labels:
        app: pod-nginx-proxy
    spec:
      containers:
      - name: ctn-nginx-proxy
        image: leetd/nginx-reverse-proxy-basic:v1.40
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: lab3
  name: svc-nginx-proxy
spec:
  type: NodePort
  selector:
    app: pod-nginx-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083